apiVersion: batch/v1
kind: Job
metadata:
  name: flask-db-upgrade
spec:
  template:
    spec:
      containers:
        - name: flask-db-upgrade
          image: flaskapi:v1.0.0
          command: ["flask","db","upgrade"]
          env:
            - name: FLASK_APP
              value: "app:app"
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: db-url
                  key: DB_URL
      restartPolicy: Never
  backoffLimit: 1
  ttlSecondsAfterFinished: null