apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-api
  labels:
    Flask: Api
spec:
  replicas: 3
  selector:
    matchLabels:
      Flask: Api
  template:
    metadata:
      name: flask-template
      labels:
        Flask: Api
    spec:
      imagePullSecrets: 
        - name: ecr-cred
      containers:
        - name: flask
          image: 977099016333.dkr.ecr.us-east-1.amazonaws.com/flaskapi:1439b104c5ec44518dab0b03936ac87c41ff4ee9
          ports:
            - containerPort: 8000
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: db-url
                  key: DB_URL
            - name: FLASK_APP
              value: "app:app"