apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-api
  labels:
    Flask: Api
spec:
  replicas: 3
  selector:
    matchLabels:
      Flask: Api
  template:
    metadata:
      name: flask-template
      labels:
        Flask: Api
    spec:
      containers:
        - name: flask
<<<<<<< HEAD
          imagePullSecrets: 
            - name: ecr-cred
=======
          image: 977099016333.dkr.ecr.us-east-1.amazonaws.com/flaskapi:c042e391741a76dfc42d41e1be2cdf0c404df579
>>>>>>> f23d49528b0516753b70d8ea6ead238e632b454c
          ports:
            - containerPort: 8000
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: db-url
                  key: DB_URL
            - name: FLASK_APP
              value: "app:app"