apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgre-deploy
  labels:
    Flask: Db
spec:
  selector:
    matchLabels:
      Flask: Db
  replicas: 1
  template:
    metadata:
      name: postgres-pod
      labels:
        Flask: Db
    spec:
      containers:
        - name: p-database
          ports:
            - containerPort: 5432

          image: postgres:13
          env:
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_PASSWORD
              value: "5164"
            - name: POSTGRES_DB
              value: apiserver
          volumeMounts:
            - name: db-storage
              mountPath: "/var/lib/postgresql/data"
      volumes:
        - name: db-storage
          persistentVolumeClaim:
            claimName: db-vol 
